package com.example.osilink.navigation

const val ROUTE_BUY = "buy"
const val ROUTE_MYHOME = "myHome"
const val ROUTE_HOME = "home"
const val ROUTE_RENT = "rent"
const val ROUTE_SELL = "sell"
const val ROUTE_CARPENTRY = "carpentry"
const val ROUTE_CLEANING = "cleaning"
const val ROUTE_ELECTRICAL = "electrical"
const val ROUTE_PLUMBING = "plumbing"
const val ROUTE_BOOKING = "booking"
const val ROUTE_LOGIN = "log_in"
const val ROUTE_SIGNUP = "sign_up"
const val ROUTE_SIGNUP_ELECTRICIAN = "sign_up_electrician"
const val ROUTE_SIGNUP_CLEANER = "sign_up_cleaner"
const val ROUTE_SIGNUP_CARPENTER = "sign_up_carpenter"
const val ROUTE_SIGNUP_PLUMBER = "sign_up_plumber"
const val ROUTE_USER_PLUMBER = "user_plumber"
const val ROUTE_USER_ELECTRICIAN = "user_electrician"
const val ROUTE_USER_CLEANER = "user_cleaner"
const val ROUTE_USER_CARPENTER = "user_carpenter"
const val ROUTE_THANK_YOU = "thank_you"
const val ROUTE_BOOKED_LIST = "booked_list"
